INSERT INTO VACADAMY_DEPARTMENT (DEPT_NAME) VALUES ('IT');
INSERT INTO VACADAMY_DEPARTMENT (DEPT_NAME) VALUES ('CSC');
INSERT INTO VACADAMY_DEPARTMENT (DEPT_NAME) VALUES ('EEE');
INSERT INTO VACADAMY_DEPARTMENT (DEPT_NAME) VALUES ('ECE');



INSERT INTO VACADAMY_STUDENTS (FIRST_NAME,LAST_NAME,EMAIL,DEPT_ID)
VALUES ('student1','student1','student1@gmail.com',1);
INSERT INTO VACADAMY_STUDENTS (FIRST_NAME,LAST_NAME,EMAIL,DEPT_ID)
VALUES ('Student2','CSC','student2@gmail.com',1);
INSERT INTO VACADAMY_STUDENTS (FIRST_NAME,LAST_NAME,EMAIL,DEPT_ID)
VALUES ('student3','IT','student3@gmail.com',2);
INSERT INTO VACADAMY_STUDENTS (FIRST_NAME,LAST_NAME,EMAIL,DEPT_ID)
VALUES ('student4','EEE','student4@gmail.com',3);
INSERT INTO VACADAMY_STUDENTS (FIRST_NAME,LAST_NAME,EMAIL,DEPT_ID)
VALUES ('student5','ECE','student5@gmail.com',4);